<?php

return [
    'state_dir' => '/var/lib/sesame-portal',
    'db_path' => '/var/lib/sesame-portal/portal.sqlite',
    'db_dsn' => null,
    'db_user' => null,
    'db_password' => null,
    'app_secret' => 'replace-with-random-secret',
    'timezone' => 'UTC',
    'locale' => 'ru',
    'base_url' => 'https://portal.example.com',
    'auth_backend_path' => '/api/sesamedvr/auth',
    'portal_update_enabled' => true,
    'portal_update_github_repo' => 'rosteleset/SesamePortal',
    'portal_update_github_ref' => 'main',
    'portal_update_github_token' => '',
    'portal_update_check_ttl_seconds' => 600,
    'portal_update_auto_check' => true,
    'portal_update_command' => 'sudo -n /usr/local/sbin/sesame-portal-update',
    'portal_update_pass_args' => false,
    'map_provider' => 'openstreetmap',
    'map_default_lat' => 47.242057,
    'map_default_lng' => 38.889615,
    'crypto_primary_key' => 'primary',
    'crypto_keys' => [
        'primary' => 'replace-with-random-secret',
    ],
    'smtp_host' => '',
    'smtp_port' => 465,
    'smtp_user' => '',
    'smtp_password' => '',
    'smtp_security' => 'ssl',
    'smtp_from_email' => '',
    'smtp_from_name' => 'Портал Артел МиК',
];
